# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 13:23
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('subtitle', models.CharField(max_length=255, null=True, verbose_name='subitle')),
                ('text', redactor.fields.RedactorField(blank=True, null=True, verbose_name='text')),
                ('text_preview', models.CharField(max_length=1000, null=True, verbose_name='text_preview')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date',),
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
