# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-21 20:06
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170225_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contains',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='contains'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=redactor.fields.RedactorField(blank=True, null=True, verbose_name='description'),
        ),
    ]
