# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[(b'en', b'English'), (b'ru', b'Russian')], default=b'en', max_length=10, verbose_name='language'),
        ),
    ]
