# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import feincms.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20170224_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', feincms.contrib.fields.JSONField(editable=False, null=True)),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('urlconf_path', models.CharField(choices=[(b'products.urls', b'Product application')], max_length=100, verbose_name='application')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicationcontent_set', to='page.Page')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
                'verbose_name_plural': 'application contents',
                'db_table': 'page_page_applicationcontent',
                'verbose_name': 'application content',
                'permissions': [],
            },
        ),
    ]
