# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_applicationcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcontent',
            name='urlconf_path',
            field=models.CharField(choices=[(b'products.urls', b'Product application'), (b'cart.urls', b'Cart application')], max_length=100, verbose_name='application'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_key',
            field=models.CharField(choices=[(b'content/pages/page.html', 'Page'), (b'content/pages/page_index.html', 'Page Index')], default=b'content/pages/page.html', max_length=255, verbose_name='template'),
        ),
    ]
