# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20170226_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcontent',
            name='urlconf_path',
            field=models.CharField(choices=[(b'products.urls', b'Product application'), (b'sales.urls', b'Sales application'), (b'cart.urls', b'Cart application')], max_length=100, verbose_name='application'),
        ),
    ]
