# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-22 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20170415_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsblock',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productsnewct',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='productsrelated',
            name='parent',
        ),
        migrations.DeleteModel(
            name='NewsBlock',
        ),
        migrations.DeleteModel(
            name='ProductsNewCT',
        ),
        migrations.DeleteModel(
            name='ProductsRelated',
        ),
    ]
