# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='content',
            field=models.TextField(max_length=1000, null=True, verbose_name='content'),
        ),
    ]
